package Vista;

import Controlador.CtrlObras;
import Modelo.Obra;
import java.util.Iterator;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author roybert
 */
public class IEliminarO extends javax.swing.JFrame {
private final Iterator<Obra> it = CtrlObras.getInstancia().getObrasArray().iterator(); /* Iterador de obras. */

private Obra aux;
  
    public IEliminarO() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Eliminar Obra de Arte");
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage()); //PROBANDO 
        
        /* Se cargan las obras existentes en el combobox.*/
        
        while(it.hasNext()){
            aux=it.next();
            ComboBoxObra.addItem(aux.getIdObra()+" "+aux.getTituloObra()); 
        }
   
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        ComboBoxObra = new javax.swing.JComboBox<>();
        labelSeleccion = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();
        botonFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eliminar Obra de Arte");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo.setText("Eliminar Obra de Arte");

        ComboBoxObra.setFocusable(false);
        ComboBoxObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxObraActionPerformed(evt);
            }
        });

        labelSeleccion.setText("Seleccionar Obra a Eliminar:");

        botonEliminar.setBackground(new java.awt.Color(246, 246, 246));
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar_md.png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminar.setFocusPainted(false);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonFinalizar.setBackground(new java.awt.Color(246, 246, 246));
        botonFinalizar.setText("Finalizar");
        botonFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonFinalizar.setFocusPainted(false);
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(botonEliminar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(ComboBoxObra, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelSeleccion)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(97, 97, 97)
                .addComponent(labelSeleccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(botonFinalizar)
                .addContainerGap())
        );

        labelTitulo.getAccessibleContext().setAccessibleParent(labelTitulo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
        IAdministracionO administraciono = new IAdministracionO();
        administraciono.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonFinalizarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
      
      
        try{
            /* Se obtiene del ComboBox la obra a eliminar*/
            
            String OElim =(String) ComboBoxObra.getSelectedItem();
            ComboBoxObra.removeItem(ComboBoxObra.getSelectedItem());
            StringTokenizer id = new StringTokenizer(OElim," ");
            String token =  id.nextToken();
          
            for (int i=0;i<CtrlObras.getInstancia().getObrasArray().size();i++){

              aux =  CtrlObras.getInstancia().getObrasArray().get(i);
              String IdObra = aux.getIdObra();

                if( token == null ? IdObra == null : token.equals(IdObra) ){
                    CtrlObras.getInstancia().getObrasArray().remove(aux); /* Se elimina la obra del arreglo de obras.*/

                }     
            }
                
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "No existen obras a eliminar.", "Ha ocurrido un error.", JOptionPane.ERROR_MESSAGE);
        }
             
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void ComboBoxObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxObraActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxObra;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelSeleccion;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables

    
}
