/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.PuntoDeInteres;
import Controlador.CtrlPuntoDeInteres;
import java.util.StringTokenizer;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author roybert
 */
public class IEliminarPI extends javax.swing.JFrame {
    
    private final Iterator<PuntoDeInteres> it = CtrlPuntoDeInteres.getInstancia().getPuntoDeInteresArray().iterator();
    private PuntoDeInteres aux;

    /**
     * Creates new form IEliminarPI
     */
    public IEliminarPI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Eliminar Punto de Interes");
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage()); //PROBANDO 
        
        /* Se cargan los puntos de interes existentes en el combobox.*/
        
        while(it.hasNext()){
            aux=it.next();
            ComboBoxPI.addItem(aux.getIdentificador()+" "+aux.getNombre()); 
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelSeleccion = new javax.swing.JLabel();
        ComboBoxPI = new javax.swing.JComboBox<>();
        botonEliminar = new javax.swing.JButton();
        botonFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo.setText("Eliminar Punto de Interes");

        labelSeleccion.setText("Seleccionar Punto de Interes a Eliminar:");

        ComboBoxPI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboBoxPI.setFocusable(false);
        ComboBoxPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxPIActionPerformed(evt);
            }
        });

        botonEliminar.setBackground(new java.awt.Color(246, 246, 246));
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar_md.png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminar.setFocusPainted(false);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonFinalizar.setBackground(new java.awt.Color(246, 246, 246));
        botonFinalizar.setText("Finalizar");
        botonFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonFinalizar.setFocusPainted(false);
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEliminar)
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSeleccion)
                    .addComponent(labelTitulo))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonFinalizar)
                    .addComponent(ComboBoxPI, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(84, 84, 84)
                .addComponent(labelSeleccion)
                .addGap(11, 11, 11)
                .addComponent(ComboBoxPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(botonFinalizar)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxPIActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        
        try{
            /* Se obtiene del ComboBox el punto de interes a eliminar*/
            
            String OElim =(String) ComboBoxPI.getSelectedItem();
            ComboBoxPI.removeItem(ComboBoxPI.getSelectedItem());
            StringTokenizer id = new StringTokenizer(OElim," ");
            String token =  id.nextToken();

            for (int i=0;i<CtrlPuntoDeInteres.getInstancia().getPuntoDeInteresArray().size();i++){

                aux =  CtrlPuntoDeInteres.getInstancia().getPuntoDeInteresArray().get(i);
                String IdPI= aux.getIdentificador();
                if( token == null ? IdPI == null : token.equals(IdPI) ){
                    CtrlPuntoDeInteres.getInstancia().getPuntoDeInteresArray().remove(aux); /* Se elimina el punto de interes del arreglo de puntos de interes.*/
                    
                }
            }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "No existen puntos de interés a eliminar.", "Ha ocurrido un error.", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
       IAdministracionPI administracionpi = new IAdministracionPI();
       administracionpi.setVisible(true); 
       this.setVisible(false);
    }//GEN-LAST:event_botonFinalizarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxPI;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelSeleccion;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
