/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtrlControlador;
import Controlador.CtrlPuntoDeInteres;
import Controlador.CtrlObras;
import Modelo.Obra;
import Modelo.PuntoDeInteres;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.StringTokenizer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Jesus Antonio
 */
public class IModificarPI extends javax.swing.JFrame {
CtrlControlador controlador; 
CtrlPuntoDeInteres controladorPI;
CtrlObras controladorObra;
private Iterator<PuntoDeInteres> it = controladorPI.getInstancia().getPuntoDeInteresArray().iterator();
private Iterator<Obra> ite = controladorObra.getInstancia().getObrasArray().iterator();
private PuntoDeInteres aux;
private Obra auxO, EauxO;
private ArrayList <Obra> ObrasPI= new ArrayList <Obra> ();
private ArrayList <Obra> ObrasPIAux= new ArrayList <Obra> ();
    /**
     * Creates new form CrearTV
     */
    public IModificarPI() {
        initComponents(); 
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Modificar Punto De Interes"); 
        
        DefaultTableModel modelo  = (DefaultTableModel) TablaPuntosDeInteres.getModel(); 
        
        while(it.hasNext()){
            aux=it.next();
            modelo.addRow(new Object[]{aux.getIdentificador(),aux.getNombre(),aux.getDisponibilidad()});       
        }
        
        while(ite.hasNext()){
            auxO = ite.next();
            ComboBoxObras.addItem(auxO.getIdObra()+" "+auxO.getTituloObra());   
        }      
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        disponibilidadpi = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        NombrePI = new javax.swing.JTextField();
        idPI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPuntosDeInteres = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DButton = new javax.swing.JRadioButton();
        NDButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxObras = new javax.swing.JComboBox();
        agregarObra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaObras = new javax.swing.JTable();
        eliminarObra = new javax.swing.JButton();
        modificarPuntoInteres = new javax.swing.JButton();
        finalizarModificarPI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        idPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPIActionPerformed(evt);
            }
        });

        jLabel4.setText("Identificador: ");

        jLabel3.setText("Ingrese propiedades del punto de interés a modificar: ");

        TablaPuntosDeInteres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_PuntoInteres", "Nombre", "Disponibilidad"
            }
        ));
        TablaPuntosDeInteres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPuntosDeInteresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPuntosDeInteres);

        jLabel2.setText("Seleccione Punto de interés a modificar: ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Modificar Punto de Interés");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Disponibilidad:");

        DButton.setBackground(new java.awt.Color(255, 255, 255));
        disponibilidadpi.add(DButton);
        DButton.setText("Disponible");
        DButton.setFocusPainted(false);

        NDButton.setBackground(new java.awt.Color(255, 255, 255));
        disponibilidadpi.add(NDButton);
        NDButton.setText("No Disponible");
        NDButton.setFocusPainted(false);

        jLabel7.setText("Agregar obras: ");

        ComboBoxObras.setFocusable(false);
        ComboBoxObras.setOpaque(false);
        ComboBoxObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxObrasActionPerformed(evt);
            }
        });

        agregarObra.setBackground(new java.awt.Color(246, 246, 246));
        agregarObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_md.png"))); // NOI18N
        agregarObra.setText("Agregar Obra");
        agregarObra.setFocusPainted(false);
        agregarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarObraActionPerformed(evt);
            }
        });

        TablaObras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Obra", "Titulo"
            }
        ));
        jScrollPane2.setViewportView(TablaObras);

        eliminarObra.setBackground(new java.awt.Color(246, 246, 246));
        eliminarObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar_md.png"))); // NOI18N
        eliminarObra.setText("Eliminar Obra");
        eliminarObra.setFocusPainted(false);
        eliminarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarObraActionPerformed(evt);
            }
        });

        modificarPuntoInteres.setBackground(new java.awt.Color(246, 246, 246));
        modificarPuntoInteres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar_md.png"))); // NOI18N
        modificarPuntoInteres.setText("Modificar");
        modificarPuntoInteres.setFocusPainted(false);
        modificarPuntoInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPuntoInteresActionPerformed(evt);
            }
        });

        finalizarModificarPI.setBackground(new java.awt.Color(246, 246, 246));
        finalizarModificarPI.setText("Finalizar");
        finalizarModificarPI.setFocusPainted(false);
        finalizarModificarPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarModificarPIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(ComboBoxObras, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(finalizarModificarPI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(34, 34, 34)
                                .addComponent(idPI, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(NDButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(NombrePI, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eliminarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(modificarPuntoInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(agregarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(176, 176, 176))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NombrePI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DButton)
                    .addComponent(NDButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboBoxObras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarObra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarObra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificarPuntoInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(finalizarModificarPI)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void finalizarModificarPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarModificarPIActionPerformed
       IAdministracionPI administracionpi = new IAdministracionPI();
       administracionpi.setVisible(true); 
       this.setVisible(false);
    }//GEN-LAST:event_finalizarModificarPIActionPerformed

    private void TablaPuntosDeInteresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPuntosDeInteresMouseClicked
           
        DefaultTableModel modelo2 = (DefaultTableModel) TablaObras.getModel();
        int filas= TablaObras.getRowCount();
        for (int i = 0; filas>i; i++) {
            modelo2.removeRow(0);
        }
        String Id = TablaPuntosDeInteres.getValueAt(TablaPuntosDeInteres.getSelectedRow(), 0).toString();
        String Nombre = TablaPuntosDeInteres.getValueAt(TablaPuntosDeInteres.getSelectedRow(), 1).toString();
        String Disp = TablaPuntosDeInteres.getValueAt(TablaPuntosDeInteres.getSelectedRow(), 2).toString();
        idPI.setText(Id);
        NombrePI.setText(Nombre);
        if(Disp == "Disponible"){
             disponibilidadpi.setSelected(DButton.getModel(), true);
        }else if(Disp == "No Disponible"){
             disponibilidadpi.setSelected(NDButton.getModel(), true);
        }
        
        for (int i=0; i < CtrlPuntoDeInteres.getInstancia().getPuntoDeInteresArray().size();i++){

            aux =  CtrlPuntoDeInteres.getInstancia().getPuntoDeInteresArray().get(i);
            String IdPI = aux.getIdentificador();

            if( Id == null ? IdPI == null : Id.equals(IdPI) ){
                DefaultTableModel modeloO = (DefaultTableModel)TablaObras.getModel();
                for(int j=0; j<aux.getObrasPuntoDeInteresArray().size(); j++){   
                    modeloO.addRow(new Object[]{aux.getObrasPuntoDeInteresArray().get(j).getIdObra(), aux.getObrasPuntoDeInteresArray().get(j).getTituloObra()});
                    ObrasPI = CtrlPuntoDeInteres.getInstancia().getPuntoDeInteresArray().get(i).getObrasPuntoDeInteresArray();
                }   
            }     
        }
    }//GEN-LAST:event_TablaPuntosDeInteresMouseClicked

    private void idPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPIActionPerformed

    private void agregarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarObraActionPerformed
         
        String O = (String) ComboBoxObras.getSelectedItem(); 
        StringTokenizer id = new StringTokenizer(O," ");
        String token =  id.nextToken();
        
        for (int i = 0; i<CtrlObras.getInstancia().getObrasArray().size();i++){

            String IdObra = CtrlObras.getInstancia().getObrasArray().get(i).getIdObra();

            if( token == null ? IdObra == null : token.equals(IdObra) ){

                DefaultTableModel modelo2 = (DefaultTableModel) TablaObras.getModel();
                modelo2.insertRow(0, new Object[]{CtrlObras.getInstancia().getObrasArray().get(i).getIdObra(),
                CtrlObras.getInstancia().getObrasArray().get(i).getTituloObra()});
                auxO = CtrlObras.getInstancia().getObrasArray().get(i);
            }
        }
    }//GEN-LAST:event_agregarObraActionPerformed

    private void eliminarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarObraActionPerformed
        
        String Id = TablaObras.getValueAt(TablaObras.getSelectedRow(), 0).toString();
        for(int i = 0; i < ObrasPI.size(); i++){
            if(Id == null ? ObrasPI.get(i).getIdObra() == null : Id.equals(ObrasPI.get(i).getIdObra())){    
                EauxO = ObrasPI.get(i);
                ((DefaultTableModel)TablaObras.getModel()).removeRow(TablaObras.getSelectedRow());
            }
        }
        
    }//GEN-LAST:event_eliminarObraActionPerformed

    private void modificarPuntoInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPuntoInteresActionPerformed
        
        aux.setIdentificador( idPI.getText());
        aux.setNombre(NombrePI.getText());
        aux.getObrasPuntoDeInteresArray().add(auxO);
        aux.getObrasPuntoDeInteresArray().remove(EauxO);
        
        if(disponibilidadpi.getSelection().equals(DButton.getModel())) {
            aux.setDisponibilidad("Disponible");
        }
        if(disponibilidadpi.getSelection().equals(NDButton.getModel())) {
            aux.setDisponibilidad("No Disponible");
        }
    
        idPI.setText(null);
        NombrePI.setText(null);
        disponibilidadpi.clearSelection();
    
        DefaultTableModel modelo2 = (DefaultTableModel) TablaObras.getModel();
        
        int filas= TablaObras.getRowCount();
        
        for (int i = 0; filas>i; i++) {
            modelo2.removeRow(0);
        }
        
    }//GEN-LAST:event_modificarPuntoInteresActionPerformed

    private void ComboBoxObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxObrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxObrasActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxObras;
    private javax.swing.JRadioButton DButton;
    private javax.swing.JRadioButton NDButton;
    private javax.swing.JTextField NombrePI;
    private javax.swing.JTable TablaObras;
    private javax.swing.JTable TablaPuntosDeInteres;
    private javax.swing.JButton agregarObra;
    private javax.swing.ButtonGroup disponibilidadpi;
    private javax.swing.JButton eliminarObra;
    private javax.swing.JButton finalizarModificarPI;
    private javax.swing.JTextField idPI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modificarPuntoInteres;
    // End of variables declaration//GEN-END:variables
}
