
package Vista;

import Controlador.CtrlControlador;
import Controlador.CtrlObras;
import Modelo.Obra;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class IModificarO extends javax.swing.JFrame {
CtrlControlador controlador;  
CtrlObras controladorObra;
private Iterator<Obra> it = controladorObra.getInstancia().getObrasArray().iterator();

private Obra aux;
    public IModificarO() {
        initComponents(); 
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Crear Tour Virtual");
        
        /* Se cargan las obras existentes en el arreglo de obras a la tabla.*/
        
        DefaultTableModel modelo = (DefaultTableModel) tablaObrasExistentes.getModel(); 
        
         while(it.hasNext()){
            aux=it.next();
            modelo.addRow(new Object[]{aux.getIdObra(),aux.getTituloObra(),aux.getAutorObra()});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idO = new javax.swing.JTextField();
        labelIngreso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaObrasExistentes = new javax.swing.JTable();
        labelSeleccion = new javax.swing.JLabel();
        labelTituloVentana = new javax.swing.JLabel();
        labelIdentificador = new javax.swing.JLabel();
        botonModificar = new javax.swing.JButton();
        botonFinalizar = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        tituloO = new javax.swing.JTextField();
        labelAutor = new javax.swing.JLabel();
        autorO = new javax.swing.JTextField();
        labelCreacion = new javax.swing.JLabel();
        añoO = new javax.swing.JTextField();
        labelUbicacion = new javax.swing.JLabel();
        ubicacionO = new javax.swing.JTextField();
        labelDescripcion = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descripcionO = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        idO.setEditable(false);

        labelIngreso.setText("Ingrese propiedades de la obra de arte: ");

        tablaObrasExistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_OBRA", "Titulo", "Autor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaObrasExistentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaObrasExistentes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaObrasExistentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaObrasExistentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaObrasExistentes);

        labelSeleccion.setText("Obras De Arte Existentes, seleccione obra a modificar:");

        labelTituloVentana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTituloVentana.setText("Modificar Obra De Arte");

        labelIdentificador.setText("Identificador:");

        botonModificar.setBackground(new java.awt.Color(246, 246, 246));
        botonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar_md.png"))); // NOI18N
        botonModificar.setText("Modificar");
        botonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificar.setFocusPainted(false);
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonFinalizar.setBackground(new java.awt.Color(246, 246, 246));
        botonFinalizar.setText("Finalizar");
        botonFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonFinalizar.setFocusPainted(false);
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });

        labelTitulo.setText("Titulo:");

        labelAutor.setText("Autor:");

        labelCreacion.setText("Año de creación:");

        labelUbicacion.setText("Ubicación");

        labelDescripcion.setText("Descripción: ");

        descripcionO.setColumns(20);
        descripcionO.setRows(5);
        jScrollPane3.setViewportView(descripcionO);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIdentificador)
                            .addComponent(labelTitulo)
                            .addComponent(labelAutor)
                            .addComponent(labelCreacion)
                            .addComponent(labelUbicacion)
                            .addComponent(labelDescripcion))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(botonModificar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(añoO, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ubicacionO, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloO, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(autorO, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idO, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(46, 46, 46))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelSeleccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(46, 46, 46))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(labelIngreso))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(labelTituloVentana)))
                .addGap(105, 169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTituloVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelIngreso)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdentificador)
                    .addComponent(idO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(tituloO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAutor)
                    .addComponent(autorO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCreacion)
                    .addComponent(añoO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUbicacion)
                    .addComponent(ubicacionO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescripcion))
                .addGap(18, 18, 18)
                .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(botonFinalizar)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
       IAdministracionO administraciono = new IAdministracionO();
       administraciono.setVisible(true); 
       this.setVisible(false);
    }//GEN-LAST:event_botonFinalizarActionPerformed

    private void tablaObrasExistentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaObrasExistentesMouseClicked
  
        String Id = tablaObrasExistentes.getValueAt(tablaObrasExistentes.getSelectedRow(), 0).toString();
        for (int i=0;i<CtrlObras.getInstancia().getObrasArray().size();i++){

              aux =  CtrlObras.getInstancia().getObrasArray().get(i);
              String IdObra = aux.getIdObra();

                if( Id == null ? IdObra == null : Id.equals(IdObra) ){
                    /* Se cargan en los campos los datos de la Obra a modificar. */
                    idO.setText(aux.getIdObra());
                    tituloO.setText(aux.getTituloObra());
                    autorO.setText(aux.getAutorObra()); 
                    añoO.setText(aux.getAñoCreacionObra());
                    ubicacionO.setText(aux.getUbicacionObra());
                    descripcionO.setText(aux.getDescripcionObra());
                }     
            }    
    }//GEN-LAST:event_tablaObrasExistentesMouseClicked

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        
        String Id = tablaObrasExistentes.getValueAt(tablaObrasExistentes.getSelectedRow(), 0).toString();
        for (int i=0;i<CtrlObras.getInstancia().getObrasArray().size();i++){      
                
            aux =  CtrlObras.getInstancia().getObrasArray().get(i);
            String IdObra = aux.getIdObra();

                if( Id == null ? IdObra == null : Id.equals(IdObra) ){
            
                    if ((idO.getText().length()!=0) && (autorO.getText().length()!=0) && (tituloO.getText().length()!=0) &&(añoO.getText().length()!=0) && (ubicacionO.getText().length()!=0)&&(descripcionO.getText().length()!=0)){
                        
                        /* Se guardan los cambios en la obra modificada.*/
                        
                        CtrlObras.getInstancia().getObrasArray().get(i).setTituloObra(tituloO.getText());
                        CtrlObras.getInstancia().getObrasArray().get(i).setAutorObra(autorO.getText());
                        CtrlObras.getInstancia().getObrasArray().get(i).setAñoCreacionObra(añoO.getText());
                        CtrlObras.getInstancia().getObrasArray().get(i).setUbicacionObra(ubicacionO.getText());
                        CtrlObras.getInstancia().getObrasArray().get(i).setDescripcionObra(descripcionO.getText());
                        
                        int row = tablaObrasExistentes.getSelectedRow();
                        ((DefaultTableModel)tablaObrasExistentes.getModel()).removeRow(row); /* Se elimina la fila previa en la tabla. */
                        ((DefaultTableModel)tablaObrasExistentes.getModel()).insertRow(row, new Object[]{aux.getIdObra(),aux.getTituloObra(),aux.getAutorObra()}); /* Se actualizan los datos de la obra en la tabla.*/
                        
                        /* Se reinician los campos de la ventana. */
                        
                        idO.setText(null);
                        tituloO.setText(null);
                        autorO.setText(null);
                        añoO.setText(null);
                        ubicacionO.setText(null);
                        descripcionO.setText(null);
                    }else{
                        JOptionPane.showMessageDialog(null, "Se deben rellenar todos los campos.", "Atención.", JOptionPane.WARNING_MESSAGE); // No pueden haber campos vacíos.
                    }
                    
                } 
        
        }
    }//GEN-LAST:event_botonModificarActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autorO;
    private javax.swing.JTextField añoO;
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JTextArea descripcionO;
    private javax.swing.JTextField idO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelCreacion;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelIdentificador;
    private javax.swing.JLabel labelIngreso;
    private javax.swing.JLabel labelSeleccion;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTituloVentana;
    private javax.swing.JLabel labelUbicacion;
    private javax.swing.JTable tablaObrasExistentes;
    private javax.swing.JTextField tituloO;
    private javax.swing.JTextField ubicacionO;
    // End of variables declaration//GEN-END:variables
}
